apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emails
  template:
    metadata:
      labels:
        app: emails
    spec:
      containers:
        - image: barbaralipnik/emails:latest
          name: emails
          ports:
            - containerPort: 8083
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: emails-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      targetPort: server
  selector:
    app: emails
